[2025-08-27T23:00:25.279+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: welcome_dag.print_date scheduled__2025-08-26T23:00:00+00:00 [queued]>
[2025-08-27T23:00:25.296+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: welcome_dag.print_date scheduled__2025-08-26T23:00:00+00:00 [queued]>
[2025-08-27T23:00:25.297+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-08-27T23:00:25.454+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): print_date> on 2025-08-26 23:00:00+00:00
[2025-08-27T23:00:25.461+0000] {standard_task_runner.py:60} INFO - Started process 124 to run task
[2025-08-27T23:00:25.467+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'welcome_dag', 'print_date', 'scheduled__2025-08-26T23:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/welcome_dag.py', '--cfg-path', '/tmp/tmp1h0_ycs0']
[2025-08-27T23:00:25.470+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask print_date
[2025-08-27T23:00:25.718+0000] {task_command.py:423} INFO - Running <TaskInstance: welcome_dag.print_date scheduled__2025-08-26T23:00:00+00:00 [running]> on host 8d32d9487e4e
[2025-08-27T23:00:26.099+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='welcome_dag' AIRFLOW_CTX_TASK_ID='print_date' AIRFLOW_CTX_EXECUTION_DATE='2025-08-26T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-26T23:00:00+00:00'
[2025-08-27T23:00:26.101+0000] {logging_mixin.py:188} INFO - Today is 2025-08-27
[2025-08-27T23:00:26.102+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-27T23:00:26.116+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=welcome_dag, task_id=print_date, execution_date=20250826T230000, start_date=20250827T230025, end_date=20250827T230026
[2025-08-27T23:00:26.283+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-27T23:00:26.312+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
