[2025-09-16T00:22:54.731+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model scheduled__2025-09-15T00:00:00+00:00 [queued]>
[2025-09-16T00:22:54.826+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_orchestration.train_model scheduled__2025-09-15T00:00:00+00:00 [queued]>
[2025-09-16T00:22:54.828+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-09-16T00:22:55.165+0000] {taskinstance.py:2191} INFO - Executing <Task(DockerOperator): train_model> on 2025-09-15 00:00:00+00:00
[2025-09-16T00:22:55.199+0000] {standard_task_runner.py:60} INFO - Started process 614 to run task
[2025-09-16T00:22:55.227+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_orchestration', 'train_model', 'scheduled__2025-09-15T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/orchestration.py', '--cfg-path', '/tmp/tmpwiybaf9p']
[2025-09-16T00:22:55.236+0000] {standard_task_runner.py:88} INFO - Job 54: Subtask train_model
[2025-09-16T00:22:55.590+0000] {task_command.py:423} INFO - Running <TaskInstance: ml_pipeline_orchestration.train_model scheduled__2025-09-15T00:00:00+00:00 [running]> on host ff4ba757c7c6
[2025-09-16T00:22:56.335+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jerr-williams' AIRFLOW_CTX_DAG_ID='ml_pipeline_orchestration' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2025-09-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-15T00:00:00+00:00'
[2025-09-16T00:22:58.772+0000] {docker.py:359} INFO - Starting docker container from image 972111245465383674563253/prediction-apps:latest
[2025-09-16T00:25:31.896+0000] {local_task_job_runner.py:121} ERROR - Received SIGTERM. Terminating subprocesses
[2025-09-16T00:25:45.877+0000] {process_utils.py:131} INFO - Sending 15 to group 614. PIDs of all processes in the group: [614]
[2025-09-16T00:25:47.935+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 614
[2025-09-16T00:26:04.612+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-09-16T00:26:30.124+0000] {docker.py:521} INFO - Stopping docker container
[2025-09-16T00:26:49.466+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=614, name='airflow task ru', status='sleeping', started='00:22:54') did not respond to SIGTERM. Trying SIGKILL
[2025-09-16T00:26:51.444+0000] {process_utils.py:86} INFO - Sending the signal 9 to group 614
[2025-09-16T00:26:51.581+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=614, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='00:22:54') (614) terminated with exit code -9
[2025-09-16T00:26:51.750+0000] {standard_task_runner.py:175} ERROR - Job 54 was killed before it finished (likely due to running out of memory)
[2025-09-16T00:26:52.175+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 143
